function [rf_model] = rfmodel(inputs,outputs,hyperparams)

rf_model = TreeBagger(hyperparams.NumTrees, inputs, outputs, ...
                      'Method', 'regression', ...
                      'MinLeafSize', hyperparams.MinLeafSize, ...
                      'NumPredictorsToSample', hyperparams.NumPredictorsToSample, ...
                      'OOBPrediction', 'on');
end

